export const data = [
  {
    uuid: 1,
    question: "Which of the following CSS properties controls text size?",
    type: "single",
    options: [
      { uuid: 1, text: "font-size", correct: true },
      { uuid: 2, text: "text-style", correct: false },
      { uuid: 3, text: "text-size", correct: false },
      { uuid: 4, text: "font-weight", correct: false },
    ],
    ans: 1,
  },
  {
    uuid: 2,
    question: "What does HTML stand for?",
    type: "single",
    options: [
      { uuid: 1, text: "HyperText Markup Language", correct: true },
      { uuid: 2, text: "Hyperlinks and Text Markup Language", correct: false },
      { uuid: 3, text: "Home Tool Markup Language", correct: false },
      { uuid: 4, text: "Hyper Transfer Markup Language", correct: false },
    ],
    ans: 1,
  },
  {
    uuid: 3,
    type: "single",
    question: "Which method is used to parse a JSON string in JavaScript?",
    options: [
      { uuid: 1, text: "JSON.stringify()", correct: false },
      { uuid: 2, text: "JSON.parse()", correct: true },
      { uuid: 3, text: "parse.JSON()", correct: false },
      { uuid: 4, text: "parseString()", correct: false },
    ],
    ans: 2,
  },
  {
    uuid: 4,
    type: "single",
    question: "Which HTTP method is used to request data from a server?",
    options: [
      { uuid: 1, text: "POST", correct: false },
      { uuid: 2, text: "DELETE", correct: false },
      { uuid: 3, text: "PUT", correct: false },
      { uuid: 4, text: "GET", correct: true },
    ],
    ans: 4,
  },
  {
    uuid: 5,
    type: "single",
    question: "Which of the following is NOT a JavaScript data type?",
    options: [
      { uuid: 1, text: "String", correct: false },
      { uuid: 2, text: "Boolean", correct: false },
      { uuid: 3, text: "Number", correct: false },
      { uuid: 4, text: "Element", correct: true },
    ],
    ans: 4,
  },
  {
    uuid: 6,
    type: "single",
    question: "What does the 'useEffect' hook do in React?",
    options: [
      { uuid: 1, text: "Directly modify the DOM", correct: false },
      { uuid: 2, text: "Schedule side effects after rendering", correct: true },
      { uuid: 3, text: "Handle user input events", correct: false },
      { uuid: 4, text: "Manage state updates", correct: false },
    ],
    ans: 2,
  },
  {
    uuid: 7,
    type: "single",
    question: "Which HTML tag is used to define an internal stylesheet?",
    options: [
      { uuid: 1, text: "<style>", correct: true },
      { uuid: 2, text: "<script>", correct: false },
      { uuid: 3, text: "<css>", correct: false },
      { uuid: 4, text: "<link>", correct: false },
    ],
    ans: 1,
  },
  {
    uuid: 8,
    type: "single",
    question: "Which of the following is a JavaScript framework?",
    options: [
      { uuid: 1, text: "Django", correct: false },
      { uuid: 2, text: "React", correct: true },
      { uuid: 3, text: "Flask", correct: false },
      { uuid: 4, text: "Laravel", correct: false },
    ],
    ans: 2,
  },
  {
    uuid: 9,
    type: "single",
    question: "What is the purpose of the 'box-sizing' property in CSS?",
    options: [
      { uuid: 1, text: "To add a border to an element", correct: false },
      {
        uuid: 2,
        text: "To control the layout and sizing of an element",
        correct: true,
      },
      {
        uuid: 3,
        text: "To change the background color of an element",
        correct: false,
      },
      { uuid: 4, text: "To set the height of an element", correct: false },
    ],
    ans: 2,
  },
  {
    uuid: 10,
    type: "single",
    question: "What does CSS stand for?",
    options: [
      { uuid: 1, text: "Creative Style Sheets", correct: false },
      { uuid: 2, text: "Cascading Style Sheets", correct: true },
      { uuid: 3, text: "Computer Style Sheets", correct: false },
      { uuid: 4, text: "Colorful Style Sheets", correct: false },
    ],
    ans: 2,
  },
];
